version: '3.1'
services:
  web:
    image: nginx:latest
    volumes:
      - ./web:/web
      - ./nginx/default.nginx:/etc/nginx/conf.d/default.conf
    restart: always
    environment:
      LETSENCRYPT_HOST: cmyk-sorter.kompjutek.site
      LETSENCRYPT_EMAIL: michalkolar.su@seznam.cz
      VIRTUAL_HOST: cmyk-sorter.kompjutek.site
networks:
  default:
    external:
      name: nginx-proxy
